services:
  postgres:
    image: postgres:16-alpine
    container_name: solarperform-db-dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: solarperform
    ports:
      - '5432:5432'
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d solarperform']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data_dev:
